### ISSUE TITLE
proto2 vs proto3

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSPipelineMsg#9]
Steve points out that proto3 is there as well.

I've read a little and I liked what I saw: they want to be more explicit, removed defaults, got rid off 'optional' (simplified internal logic), support for Go, proto3 is production now (proto2 is 'maintained')

Please consider WHY and IF we should stick with proto2 (moving now would be easy).

https://stackoverflow.com/questions/36742747/proto2-vs-proto3-in-c-sharp

**Comment by romanchyla** [comment]
and did I mention i like the presence of some default types? espeically the timestamp

**Comment by romanchyla** [comment]
...hm, so maybe it's 3.3 in the end? cause the dockerfile installs python 3.3.0 - though the proto files specify proto2 syntax

**Comment by marblestation** [comment]
It was proto2, no reason to stay with it so I upgraded to version 3 in commit e4fe93ab16e0fd39b72dd199493d7a7df47cd9df
